# Generated by Django 5.1.4 on 2025-02-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0004_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='is_executed',
        ),
    ]
