# Generated by Django 5.1.4 on 2025-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0005_remove_commands_is_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='command_response',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='commands',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
    ]
