# Generated by Django 5.1.4 on 2025-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0007_uploads_is_downloaded_alter_uploads_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
    ]
