# Generated by Django 5.1.4 on 2025-02-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0008_uploads_chunk_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='is_downloaded',
        ),
    ]
