# Generated by Django 5.1.4 on 2025-02-16 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0009_remove_uploads_is_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='chunk_index',
        ),
        migrations.CreateModel(
            name='HexForDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_side.uploads')),
            ],
        ),
    ]
