# Generated by Django 5.1.4 on 2025-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0010_remove_uploads_chunk_index_hexfordownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexfordownload',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
