# Generated by Django 5.1.4 on 2025-02-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0012_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
