# Generated by Django 5.1.4 on 2025-02-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0013_downloads_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
