# Generated by Django 5.1.4 on 2025-02-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0014_downloads_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloads',
            old_name='finished',
            new_name='is_finished',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='hex',
        ),
    ]
