# Generated by Django 5.1.4 on 2025-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0016_uploads_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='domain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
