# Generated by Django 5.1.4 on 2025-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0017_clients_domain_clients_password_clients_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='id_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
