# Generated by Django 5.1.4 on 2025-03-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0019_rename_last_updated_clients_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='address',
            new_name='ip_adress',
        ),
    ]
