# Generated by Django 5.1.4 on 2025-03-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0020_rename_address_clients_ip_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
