# Generated by Django 5.1.4 on 2025-03-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0021_rename_ip_adress_clients_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commands',
            old_name='command_response',
            new_name='response',
        ),
    ]
