# Generated by Django 5.1.4 on 2025-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0022_rename_command_response_commands_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='interval',
            field=models.IntegerField(default=5),
        ),
    ]
