# Generated by Django 5.1.4 on 2025-04-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0023_clients_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('files', models.JSONField(default=list)),
                ('folders', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_side.clients')),
            ],
        ),
    ]
