# Generated by Django 5.1.4 on 2025-04-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_side', '0024_filemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='is_drive',
            field=models.BooleanField(default=False),
        ),
    ]
